project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('syllabus.urls')),
]

syllabus/urls.py
from django.urls import path
from .views import *
from syllabus import views_auth

urlpatterns = [
    path('', home_view, name='home'),
    path('create/', create_syllabus_view, name='create_syllabus'),
    path('correspondence/<int:syllabus_id>/', correspondence, name='correspondence'),
    path('delete_learning_outcome/<int:syllabus_id>/<int:outcome_id>/', delete_learning_outcome, name='delete_learning_outcome'),
    path('thematic_plan/<int:syllabus_id>/', thematic_plan, name='thematic_plan'),
    path('delete_thematic_plan/<int:syllabus_id>/<int:plan_id>/', delete_thematic_plan, name='delete_thematic_plan'),
    path('evaluation_system/<int:syllabus_id>/', evaluation_system, name='evaluation_system'),
    path('delete_evaluation_system/<int:syllabus_id>/<int:system_id>/', delete_evaluation_system, name='delete_evaluation_system'),
    path('literature_list/<int:syllabus_id>/', literature_list, name='literature_list'),
    path('philosophy_and_policy/<int:syllabus_id>/', philosophy_and_policy, name='philosophy_and_policy'),
    path('register/', views_auth.registration, name='register'),
    path('login/', views_auth.login_view, name='login'),
    path('logout/', views_auth.logout_view, name='logout'),
    path('account/', account, name='account'),
    path('syllabus/', syllabus_list, name='syllabus_list'),
    path('syllabus/<int:syllabus_id>/', syllabus_detail_edit, name='syllabus_detail_edit'),
    path('syllabus/<int:syllabus_id>/delete/', delete_syllabus, name='delete_syllabus'),
    path('download_syllabus_word_ru/<int:syllabus_id>/', download_syllabus_word_ru, name='download_syllabus_word_ru'),
    path('delete_literature/<int:syllabus_id>/<int:literature_id>/', delete_literature, name='delete_literature'),

]

syllabus/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models


class Discipline(models.Model):
    code = models.CharField(max_length=20, unique=True, verbose_name='Код')
    name = models.CharField(max_length=255, verbose_name='Дисциплина')

    def __str__(self):
        return f'{self.code} - {self.name}'

    class Meta:
        verbose_name = 'Дисциплина'
        verbose_name_plural = 'Дисциплины'


class EducationLevel(models.Model):
    name = models.CharField(max_length=255, verbose_name='Уровень обучения')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Уровень обучения'
        verbose_name_plural = 'Уровень обучения'


class Language(models.Model):
    name = models.CharField(max_length=255, verbose_name='Язык обучения')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Язык обучения'
        verbose_name_plural = 'Язык обучения'


class Teacher(models.Model):
    full_name = models.CharField(max_length=255, verbose_name='ФИО')
    email = models.EmailField(verbose_name='Email', unique=True)
    position = models.CharField(max_length=100, verbose_name='Должность', default='Преподаватель')

    def __str__(self):
        return f'{self.full_name}'

    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'


class LanguageProficiency(models.Model):
    level = models.CharField(max_length=50, verbose_name='Уровень владения языком')

    def __str__(self):
        return self.level

    class Meta:
        verbose_name = 'Уровень владения языком'
        verbose_name_plural = 'Уровень владения языком'


class TeachingFormat(models.Model):
    format_name = models.CharField(max_length=50, verbose_name='Формат обучения')

    def __str__(self):
        return self.format_name

    class Meta:
        verbose_name = 'Формат обучения'
        verbose_name_plural = 'Формат обучения'


class Director(models.Model):
    full_name = models.CharField(max_length=255, verbose_name='ФИО')
    email = models.EmailField(verbose_name='Email', unique=True)
    phone_number = models.CharField(max_length=15, verbose_name='Телефонный номер', blank=True, null=True)
    position = models.CharField(max_length=100, verbose_name='Должность', blank=True, null=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Директор'
        verbose_name_plural = 'Директоры'


class Approval(models.Model):
    syllabus_item = models.ForeignKey('Syllabus', on_delete=models.CASCADE, related_name='approvals', verbose_name='Силлабус')
    director = models.ForeignKey('Director', on_delete=models.CASCADE, verbose_name='Директор')

    def __str__(self):
        return f'{self.syllabus_item.name} - {self.director.full_name}'

    class Meta:
        verbose_name = 'Согласование'
        verbose_name_plural = 'Согласовывание'


class Syllabus(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, verbose_name='Название силлабуса')
    discipline = models.ForeignKey('Discipline', on_delete=models.CASCADE, verbose_name='Дисциплина')
    education_level = models.ForeignKey('EducationLevel', on_delete=models.CASCADE, verbose_name='Уровень обучения')
    language = models.ForeignKey('Language', on_delete=models.CASCADE, verbose_name='Язык обучения')
    teacher = models.ForeignKey('Teacher', on_delete=models.CASCADE, verbose_name='Преподаватель')
    ects = models.IntegerField(verbose_name='Кредиты ECTS')
    total_hours = models.IntegerField(verbose_name='Всего часов')
    classroom_hours = models.IntegerField(verbose_name='Аудиторные часы')
    iw_hours = models.IntegerField(verbose_name='Самостоятельная работа (СРОП, СРО)')
    semester = models.IntegerField(verbose_name='Семестр')
    language_proficiency = models.ForeignKey('LanguageProficiency', on_delete=models.CASCADE, verbose_name='Уровень владения языком')
    prerequisites = models.CharField(max_length=255, verbose_name='Пререквизиты')
    educational_program = models.CharField(max_length=255, verbose_name='Образовательная программа')
    teaching_format = models.ForeignKey('TeachingFormat', on_delete=models.CASCADE, verbose_name='Формат обучения')
    time_class = models.CharField(max_length=255, verbose_name='Время и место проведения занятий')
    course_goal = models.TextField(verbose_name='Цель курса', default='Здесь может быть цель курса')
    approvals_syllabus = models.ManyToManyField('Director', through='Approval', blank=True, related_name='syllabus_approvals', verbose_name='Согласование')
    from_asu_repository = models.BooleanField(default=False, verbose_name='На основе ASU репозитории')

    def __str__(self):
        return f'{self.discipline.name} - {self.name}'

    class Meta:
        verbose_name = 'Силлабус'
        verbose_name_plural = 'Силлабус'


class LearningOutcome(models.Model):
    syllabus = models.ForeignKey(Syllabus, on_delete=models.CASCADE, null=True)
    course_description = models.TextField(verbose_name='Описание курса', null=True)
    learning_outcome_course = models.TextField(verbose_name='Результаты обучения курса (РО курса)', null=True)
    learning_outcome_program = models.TextField(verbose_name='Результаты обучения образоватильной программы (РО ОП)', null=True)

    def __str__(self):
        syllabus_name = self.syllabus.name if self.syllabus else "No Syllabus"
        return f'{syllabus_name} - {self.course_description}'

    class Meta:
        verbose_name = 'Результат обучения'
        verbose_name_plural = 'Результат обучения'


class ThematicPlan(models.Model):
    syllabus = models.ForeignKey('Syllabus', on_delete=models.CASCADE, verbose_name='Силлабус', null=True)
    week = models.IntegerField(verbose_name='Неделя', default=0)
    topic = models.CharField(max_length=255, verbose_name='Тема / модуль')
    ro = models.CharField(max_length=255, verbose_name='РО курса, РО ОП', null=True)
    qm = models.CharField(max_length=255, verbose_name='Вопросы по теме/ модулю', null=True)
    tasks = models.CharField(max_length=255, verbose_name='Задания', null=True)
    lit = models.CharField(max_length=255, verbose_name='Литература', null=True)
    so = models.CharField(max_length=255, verbose_name='Структура оценок', null=True)

    def __str__(self):
        return f'{self.syllabus.name} - {self.topic}'

    class Meta:
        verbose_name = 'Тематический план'
        verbose_name_plural = 'Тематические планы'


class EvaluationSystem(models.Model):
    syllabus = models.ForeignKey('Syllabus', on_delete=models.CASCADE, verbose_name='Силлабус', null=True)
    tm = models.CharField(max_length=255, verbose_name='Тема / модуль', null=True)
    mp = models.CharField(max_length=255, verbose_name='Максимальный процент (%)', null=True)
    mv = models.CharField(max_length=255, verbose_name='Максимальный вес (%)', null=True)
    tb = models.CharField(max_length=255, verbose_name='Итого в баллах', null=True)
    vk = models.CharField(max_length=255, verbose_name='Всего за курс', null=True)

    def __str__(self):
        return f'{self.syllabus.name} - {self.tm}'

    class Meta:
        verbose_name = 'Система оценивания курса'
        verbose_name_plural = 'Системы оценивания курса'


class Literature(models.Model):
    syllabus = models.ForeignKey('Syllabus', on_delete=models.CASCADE, verbose_name='Силлабус')
    title = models.CharField(max_length=255, verbose_name='Обязательная литература', null=True, blank=True)
    author = models.CharField(max_length=255, verbose_name='Интернет ресурсы', null=True, blank=True)

    def __str__(self):
        return f'{self.syllabus.name} - {self.title}'

    class Meta:
        verbose_name = 'Литература'
        verbose_name_plural = 'Список литературы'


class PhilosophyAndPolicy(models.Model):
    syllabus = models.OneToOneField('Syllabus', on_delete=models.CASCADE, verbose_name='Силлабус')
    philosophy = models.TextField(verbose_name='Философия преподавания и обучения')
    policy = models.TextField(verbose_name='Политика курса')

    def __str__(self):
        return f'{self.syllabus.name} - Философия и политика курса'

    class Meta:
        verbose_name = 'Философия и политика курса'
        verbose_name_plural = 'Философия и политика курса'


syllabus/forms.py
from django import forms
from .models import *


class SyllabusForm(forms.ModelForm):
    class Meta:
        model = Syllabus
        exclude = ['created_by']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class LearningOutcomeForm(forms.ModelForm):
    class Meta:
        model = LearningOutcome
        fields = ['course_description', 'learning_outcome_course', 'learning_outcome_program']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class ThematicPlanForm(forms.ModelForm):
    class Meta:
        model = ThematicPlan
        fields = ['week', 'topic', 'ro', 'qm', 'tasks', 'lit', 'so']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class EvaluationSystemForm(forms.ModelForm):
    class Meta:
        model = EvaluationSystem
        fields = ['tm', 'mp', 'mv', 'tb', 'vk']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class LiteratureForm(forms.ModelForm):
    class Meta:
        model = Literature
        fields = ['title', 'author']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class PhilosophyAndPolicyForm(forms.ModelForm):
    class Meta:
        model = PhilosophyAndPolicy
        fields = ['philosophy', 'policy']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

syllabus/templates/account.html
{% extends 'base.html' %}

{% block title %}Личный кабинет - {{ block.super }}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <h1>Личный кабинет</h1>
                <p class="lead">Добро пожаловать, {{ user.first_name }}!</p>
                <p>Ваш email: {{ user.username }}</p>
                <p><a class="btn btn-danger" href="/logout">Выйти</a></p>
            </div>
        </div>
    </div>
{% endblock %}

syllabus/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Syllabus-AlmaU{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style="min-height: 100vh; display: flex; flex-direction: column;">
    <header class="bg-dark text-white p-2">
        <div class="container">
            <h3>{% block header %}Syllabus{% endblock %}</h3>
        </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'syllabus_list' %}">Мои силлабусы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account' %}">Профиль</a>
                    </li>
                </ul>
            {% else %}
                <a class="btn btn-primary ml-auto" href="{% url 'login' %}" role="button">Войти в систему</a>
            {% endif %}
        </div>
    </nav>

    <main class="container mt-4 flex-grow-1" style="min-height: calc(100vh - 160px);">
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-dark text-white p-4">
        <div class="container">
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

syllabus/templates/correspondence.html
{% extends 'base.html' %}

{% block content %}
    <h3>Шаг 2. Заполните описание курса и Таблицу соответствия Результатов обучения курса Результатам обучения образовательной программы.</h3>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>

                <h2 class="mt-4"></h2>
                <div class="table-responsive">
                    <table class="table table-bordered table-fixed">
                        <thead>
                            <tr>
                                <th>Описание курса</th>
                                <th>Результаты обучения курса (РО курса)</th>
                                <th>Результаты обучения образовательной программы (РО ОП)</th>
                                <th>Действия</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for learning_outcome in syllabus.learningoutcome_set.all %}
                                <tr>
                                    <td>{{ learning_outcome.course_description }}</td>
                                    <td>{{ learning_outcome.learning_outcome_course }}</td>
                                    <td>{{ learning_outcome.learning_outcome_program }}</td>
                                    <td>
                                    <form method="post" action="{% url 'delete_learning_outcome' syllabus_id=syllabus.id outcome_id=learning_outcome.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
                                    </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <a class="btn btn-secondary mt-3" href="{% url 'create_syllabus' %}">Назад</a>
                <a class="btn btn-secondary mt-3" href="{% url 'thematic_plan' syllabus_id=syllabus.id %}">Далее</a>
            </div>
        </div>
    </div><br/><br/>
{% endblock %}

syllabus/templates/create_syllabus.html
{% extends 'base.html' %}

{% block title %}Создать силлабус - {{ block.super }}{% endblock %}

{% block content %}
    <h3>Шаг 1. Заполните основную часть Силлабуса.</h3>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
                </form>
                <a class="btn btn-secondary mt-3" href="{% url 'home' %}">Вернуться на главную</a>
            </div>
        </div>
    </div><br/><br/>
{% endblock %}

syllabus/templates/delete_syllabus.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h3 class="mb-4">Удаление силлабуса</h3>
        <p>Вы уверены, что хотите удалить силлабус "{{ syllabus.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'syllabus_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

syllabus/templates/evaluation_system.html
{% extends 'base.html' %}

{% block content %}
    <h3>Шаг 4. Заполните систему оценивания курса:</h3>
    <div class="container mt-5">
        <form method="post" enctype="multipart/form-data" class="mt-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>

        <h2 class="mt-4"></h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Тема / модуль</th>
                    <th>Максимальный процент (%)</th>
                    <th>Максимальный вес (%)</th>
                    <th>Итого в баллах</th>
                    <th>Всего за курс</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for evaluation_system in evaluation_systems %}
                    <tr>
                        <td>{{ evaluation_system.tm }}</td>
                        <td>{{ evaluation_system.mp }}</td>
                        <td>{{ evaluation_system.mv }}</td>
                        <td>{{ evaluation_system.tb }}</td>
                        <td>{{ evaluation_system.vk }}</td>
                               <td>
<form method="post" action="{% url 'delete_evaluation_system' syllabus_id=syllabus.id system_id=evaluation_system.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
</form>
                               </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a class="btn btn-secondary mt-3" href="{% url 'thematic_plan' syllabus_id=syllabus.id %}">Назад</a>
        <a class="btn btn-secondary mt-3" href="{% url 'literature_list' syllabus_id=syllabus.id %}">Далее</a>
    </div><br/><br/>
{% endblock %}

syllabus/templates/home.html
{% extends 'base.html' %}

{% block title %}Главная - {{ block.super }}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="display-4">Добро пожаловать!</h1>
        <p class="lead">Это главная страница вашего приложения. Здесь вы можете управлять своими силлабусами.</p>
        <hr class="my-4">
        {% if request.user.is_authenticated %}
            <p>Если у вас еще нет силлабуса, вы можете создать новый, нажав на кнопку ниже.</p>
            <a class="btn btn-primary btn-lg" href="{% url 'create_syllabus' %}" role="button">Создать новый силлабус</a>
        {% else %}
            <p>Для создания силлабуса войдите в систему.</p>
            <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Войти в систему</a>
        {% endif %}
    </div>
{% endblock %}

syllabus/templates/literature_list.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="mb-4">Шаг 5. Заполните список литературы.</h3>
    <div class="container mt-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>

        <h2 class="mt-5"></h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Обязательная литература</th>
                    <th>Интернет ресурсы</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for literature in literature_list %}
                    <tr>
                        <td>{{ literature.title }}</td>
                        <td>{{ literature.author }}</td>
                                                        <td>
<form method="post" action="{% url 'delete_literature' syllabus_id=syllabus.id literature_id=literature.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
</form>
                                    </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a class="btn btn-secondary mt-3" href="{% url 'evaluation_system' syllabus_id=syllabus.id %}">Назад</a>
        <a class="btn btn-secondary mt-3" href="{% url 'philosophy_and_policy' syllabus_id=syllabus.id %}">Далее</a>
    </div><br/><br/>
{% endblock %}

syllabus/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="mb-4">Авторизация</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label">Email адрес</label>
                        <input name="email" type="email" class="form-control" id="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input name="password" type="password" class="form-control" id="password" required>
                    </div>
                    {% if message %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
                <p class="mt-3">Еще нет аккаунта? <a href="{% url 'register' %}">Зарегистрируйтесь</a> здесь.</p>
            </div>
        </div>
    </div>
{% endblock %}

syllabus/templates/philosophy_and_policy.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="mb-4">Шаг 6. Заполните Философию преподавания и обучения, Политику курса.</h2>

    <form method="post" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form><br/><br/>

{% endblock %}

syllabus/templates/registration.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="mb-4">Регистрация</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label">Email адрес</label>
                        <input name="email" type="email" class="form-control" id="email" placeholder="name@example.com" required>
                    </div>
                    <div class="mb-3">
                        <label for="username" class="form-label">ФИО</label>
                        <input name="username" type="text" class="form-control" id="username" placeholder="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input name="password" type="password" class="form-control" id="password" placeholder="password" required>
                    </div>
                    <div class="mb-3">
                        <label for="password2" class="form-label">Подтвердите пароль</label>
                        <input name="password2" type="password" class="form-control" id="password2" placeholder="confirm password" required>
                    </div>
                    {% if message %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </form>
                <p class="mt-3">Уже есть аккаунт? <a href="{% url 'login' %}">Войдите</a> здесь.</p>
            </div>
        </div>
    </div>
{% endblock %}

syllabus/templates/syllabus_detail_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h3 class="mb-4">Редактировать Силлабус</h3>
        <form method="post" class="mb-4">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock %}

syllabus/templates/syllabus_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h3 class="mb-4">Мои силлабусы</h3>
        <ul class="list-group">
            {% for syllabus in syllabuses %}
                <li class="list-group-item">
                    {{ syllabus.name }}
                    <a href="{% url 'delete_syllabus' syllabus.id %}" class="btn btn-danger btn-sm float-right">Удалить</a>
                    <a href="{% url 'syllabus_detail_edit' syllabus.id %}" class="btn btn-primary btn-sm float-right mr-2">Редактировать</a>
                    <a href="{% url 'download_syllabus_word_ru' syllabus.id %}" class="btn btn-success btn-sm float-right mr-2">Скачать</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

syllabus/templates/thematic_plan.html
{% extends 'base.html' %}

{% block content %}
    <h3>Шаг 3. Заполните тематический план:</h3>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
                </form>

                <h2 class="mt-4"></h2>
                <div class="table-responsive">
                    <table class="table table-bordered table-fixed">
                        <thead>
                            <tr>
                                <th>Неделя</th>
                                <th>Тема / модуль</th>
                                <th>РО курса, РО ОП</th>
                                <th>Вопросы по теме / модулю</th>
                                <th>Задания</th>
                                <th>Литература</th>
                                <th>Структура оценок</th>
                                <th>Действия</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for thematic_plan in thematic_plans %}
                                <tr>
                                    <td>{{ thematic_plan.week }}</td>
                                    <td>{{ thematic_plan.topic }}</td>
                                    <td>{{ thematic_plan.ro }}</td>
                                    <td>{{ thematic_plan.qm }}</td>
                                    <td>{{ thematic_plan.tasks }}</td>
                                    <td>{{ thematic_plan.lit }}</td>
                                    <td>{{ thematic_plan.so }}</td>
                               <td>
                                    <form method="post" action="{% url 'delete_thematic_plan' syllabus_id=syllabus.id plan_id=thematic_plan.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Удалить</button>
                                    </form>
                               </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <a class="btn btn-secondary mt-3" href="{% url 'correspondence' syllabus_id=syllabus.id %}">Назад</a>
                <a class="btn btn-secondary mt-3" href="{% url 'evaluation_system' syllabus_id=syllabus.id %}">Далее</a>
            </div>
        </div>
    </div><br/><br/>
{% endblock %}